server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #注册的地址
        server-addr: 192.168.244.135:1111

management:
  endpoint:
    web:
      exposure:
        include: '*'
